#!/usr/bin/bash
# Config file for all scripts


# General 
MYIP=`hostname -I | sed 's/ /,/g' | rev | cut -c2- | rev`
MYHOST=`hostname -A | sed 's/ /,/g' | rev | cut -c2- | rev`
SESSION=ham
AXPORT=wl2k
KISSTMP=/tmp/kisstnc

# Pat specific
P_FIG="Pat"

# Direwolf specific
D_FIG="Direwolf"

# Mobilinkd specific
M_FIG="Mobilinkd"
RFNAME="Mobilinkd TNC3"
RFDEV=/dev/rfcomm0
RFMAC=34:81:F4:70:71:15
RFCH=6
